"""Turning a :class:`~comfygmx.nodes.base.Plan` into a bash script, and running it.

The exact same renderer feeds the UI's "copy this command" popover and the
subprocess, so there is never a preview that drifts from what was executed.
"""

from __future__ import annotations

import io
import os
import re
import shlex
import signal
import subprocess
import threading
import time
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple

from .nodes.base import Step

STEP_MARKER = "@@COMFYGMX"
_MARKER_RE = re.compile(rf"^{re.escape(STEP_MARKER)} (BEGIN|END) (\d+)(?: rc=(-?\d+))?$")


def _heredoc_tag(text: str, tag: str) -> str:
    # Pick a tag the payload cannot contain.
    while tag in text:
        tag += "_"
    return tag


def _heredoc(text: str, tag: str) -> str:
    tag = _heredoc_tag(text, tag)
    body = text if text.endswith("\n") else text + "\n"
    return f"<<'{tag}'\n{body}{tag}"


def substitute_tool(step: Step, command: str) -> List[str]:
    """Replace the logical binary name in argv[0] with the resolved command.

    The command may itself be several words -- ``python -m COBY`` or
    ``mpirun -np 4 gmx_mpi`` -- so it is split the way a shell would.
    """
    argv = list(step.argv)
    if not argv or not command:
        # tool "shell" resolves to an empty command: argv is already concrete.
        return argv
    if step.shell or step.own_command:
        return argv
    try:
        head = shlex.split(command) or [command]
    except ValueError:
        head = [command]
    return head + argv[1:]


def render_step(step: Step, command: str) -> Dict[str, str]:
    """A single step as {command, stdin} with the tool already substituted."""
    if step.shell:
        # Shell steps opt in to substitution with a {cmd} placeholder, so a
        # configured gmx_mpi still reaches a piped command.
        rendered = (step.argv[0] if step.argv else "").replace("{cmd}", command)
    else:
        argv = list(step.wrap) + substitute_tool(step, command)
        rendered = " ".join(shlex.quote(str(a)) for a in argv)
    return {"label": step.label, "command": rendered, "stdin": step.stdin or ""}


def render_script(
    steps: Iterable[Step],
    workdir: Path,
    resolve: Callable[[str], Any],
    nice: bool = True,
    trace: bool = True,
) -> str:
    """Full bash script for a node: preludes, markers, heredocs and all."""
    lines: List[str] = [
        "#!/usr/bin/env bash",
        "# Generated by Comfy-gmx. Safe to run by hand.",
        "set -o pipefail",
        "export LC_ALL=C",          # keep decimal points from becoming commas
        "export GMX_MAXBACKUP=-1",  # no #file.1# clutter inside a run directory
        f"cd {shlex.quote(str(workdir))}",
        "",
    ]
    if nice:
        # ionice is Linux only. Asking for it unconditionally made every step on
        # a Mac fail with "ionice: command not found" before it ran anything.
        lines += [
            '__nice="nice -n 10"',
            'command -v ionice >/dev/null 2>&1 && __nice="$__nice ionice -c2 -n7"',
            "",
        ]
    prefix = "$__nice " if nice else ""
    for index, step in enumerate(steps):
        tool = resolve(step.tool)
        rendered = render_step(step, tool.command)
        # A step with no label of its own is described by its command -- but a
        # command carrying a several-line value (a table of residue ranges, a
        # membrane recipe) has newlines in it, and only the first line of the
        # comment would stay a comment. The rest became lines the shell tried
        # to run, and the script died on "CP:: command not found" before it
        # reached the real work. Flattened to one line here.
        label = step.label or " ".join(rendered["command"].split())[:60]
        if trace:
            lines.append(f'echo "{STEP_MARKER} BEGIN {index}"')
        lines.append(f"# --- {label} ---")
        lines.append("(")
        if tool.prelude:
            lines.extend("  " + ln for ln in tool.prelude.splitlines())
        body = rendered["command"]
        if prefix and not step.shell:
            body = prefix + body
        if step.stdin:
            # The heredoc body and its terminator must stay unindented, so only
            # the command itself is indented into the subshell.
            tag = _heredoc_tag(step.stdin, "COMFY_IN")
            opener = f"{body} <<'{tag}'".splitlines() or [""]
            lines.append("  " + opener[0])
            lines.extend(opener[1:])
            lines.extend(step.stdin.rstrip("\n").split("\n"))
            lines.append(tag)
        else:
            # Only the first line is indented into the subshell. Indenting the
            # rest would push two spaces inside any quoted value that spans
            # lines, so a block passing a several-line box as an argument
            # handed the program a table with every line after the first
            # silently shifted. The shell does not care where a continuation
            # line starts, so nothing is lost by leaving them alone.
            body_lines = body.splitlines() or [""]
            lines.append("  " + body_lines[0])
            lines.extend(body_lines[1:])
        lines.append(")")
        lines.append("__rc=$?")
        if trace:
            lines.append(f'echo "{STEP_MARKER} END {index} rc=$__rc"')
        if not step.allow_fail:
            lines.append(
                'if [ "$__rc" -ne 0 ]; then '
                f'echo "step {index} ({label}) failed with exit code $__rc" >&2; '
                'exit "$__rc"; fi'
            )
        lines.append("")
    lines.append("exit 0")
    return "\n".join(lines)


def render_manual(steps: Iterable[Step], workdir: Path, resolve: Callable[[str], Any]) -> str:
    """The copy-paste form shown in the UI: no markers, no nice, no error traps."""
    blocks: List[str] = [f"cd {shlex.quote(str(workdir))}"]
    last_prelude = ""
    for step in steps:
        tool = resolve(step.tool)
        if tool.prelude and tool.prelude != last_prelude:
            blocks.append(tool.prelude)
            last_prelude = tool.prelude
        rendered = render_step(step, tool.command)
        body = rendered["command"]
        if step.stdin:
            body = f"{body} {_heredoc(step.stdin, 'EOF')}"
        blocks.append(body)
    return "\n\n".join(b for b in blocks if b.strip())


#: ANSI escape sequences -- colour, cursor moves. Tools emit them even into a
#: pipe, and a <pre> renders them as literal junk.
_ANSI_RE = re.compile(r"\x1b\[[0-9;?]*[ -/]*[@-~]|\x1b[@-_]")

#: Everything else that is not printable and not a tab.
_CONTROL_RE = re.compile(r"[\x00-\x08\x0b-\x1f\x7f]")


def clean_output(text: str) -> str:
    """A line as a terminal would have shown it.

    Progress indicators do not all repaint the same way. curl rewinds with a
    carriage return, which the reader below treats as a redraw; conda, writing
    to a pipe, spells its spinner with backspaces instead and sends the whole
    thing as one line::

        Collecting package metadata (repodata.json): / \x08\x08- \x08\x08\\ \x08\x08done

    A terminal applies those and shows "done". A <pre> shows the backspaces,
    which is what "the output looks buggy" turns out to mean. So they are
    applied here, colour codes are dropped, and any other control character
    goes with them.
    """
    if "\x1b" in text:
        text = _ANSI_RE.sub("", text)
    if "\x08" in text:
        out: List[str] = []
        for char in text:
            if char == "\x08":
                if out:
                    out.pop()
            else:
                out.append(char)
        text = "".join(out)
    return _CONTROL_RE.sub("", text)


class ProcessHandle:
    """A running bash script whose combined output is streamed line by line."""

    #: How often a progress redraw is forwarded, at most. conda's spinner
    #: repaints many times a second and every repaint is a separate write.
    PROGRESS_INTERVAL = 0.2

    def __init__(
        self,
        script: str,
        workdir: Path,
        on_line: Callable[[str], None],
        on_step: Optional[Callable[[str, int, Optional[int]], None]] = None,
        env: Optional[Dict[str, str]] = None,
        on_progress: Optional[Callable[[str], None]] = None,
        on_waiting: Optional[Callable[[bool], None]] = None,
    ):
        self.script = script
        self.workdir = Path(workdir)
        self.on_line = on_line
        self.on_step = on_step
        #: Where carriage-return redraws go -- a progress bar repainting itself
        #: rather than a new line. Without somewhere separate to put them they
        #: arrive as ordinary lines, because Python's universal-newline mode
        #: treats a lone CR as a line ending: one conda solve becomes several
        #: hundred near-identical lines, which scrolls the real output away and
        #: eventually pushes the start of it out of the log buffer entirely.
        self.on_progress = on_progress
        #: Called with True when something in the script is sitting there
        #: waiting for somebody to type an answer, and False when it stops.
        self.on_waiting = on_waiting
        self.env = env
        self.proc: Optional[subprocess.Popen] = None
        self.returncode: Optional[int] = None
        self._cancelled = False
        self._lock = threading.Lock()
        #: The process group every command of this step runs in. Killing the
        #: group, not just the one process we started, is the whole point: the
        #: script starts each step in a `( ... )` subshell, so the bash we
        #: launched is rarely the thing that is actually busy.
        self.pgid: Optional[int] = None
        #: How many times somebody has asked this to stop. The first ask is
        #: polite, the second one is not.
        self._stops = 0
        #: Inode of our end of the stdin pipe, so we can tell "some process is
        #: blocked reading a pipe" from "blocked reading OUR pipe".
        self._stdin_ino: Optional[int] = None
        self._typed = False
        self.waiting = False

    def run(self) -> int:
        self.workdir.mkdir(parents=True, exist_ok=True)
        script_path = self.workdir / "_comfygmx_step.sh"
        script_path.write_text(self.script)
        script_path.chmod(0o755)

        environ = dict(os.environ)
        environ.setdefault("PYTHONUNBUFFERED", "1")
        environ["LC_ALL"] = "C"
        if self.env:
            environ.update(self.env)

        with self._lock:
            if self._cancelled:
                self.returncode = 130
                return 130
            self.proc = subprocess.Popen(
                ["bash", str(script_path)],
                cwd=str(self.workdir),
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                # A pipe rather than /dev/null, so that a command which stops
                # to ask a question can be answered from the terminal drawer
                # instead of the run being lost. Nothing is written to it
                # unless somebody types; the watcher below closes it after a
                # while if nobody does, which is exactly what /dev/null used
                # to do straight away.
                stdin=subprocess.PIPE,
                text=True,
                bufsize=1,
                env=environ,
                start_new_session=True,
            )
            # start_new_session makes the child the leader of its own group,
            # so its pid IS the group id. Read it back anyway in case that
            # ever stops being true.
            try:
                self.pgid = os.getpgid(self.proc.pid)
            except OSError:
                self.pgid = self.proc.pid
            try:
                self._stdin_ino = os.fstat(self.proc.stdin.fileno()).st_ino
            except (OSError, AttributeError, ValueError):
                self._stdin_ino = None
        watcher = threading.Thread(target=self._watch_input, daemon=True,
                                   name="stdin-watch")
        watcher.start()
        assert self.proc.stdout is not None
        self._pump(self.proc.stdout)
        self.proc.wait()
        self.eof()
        self._set_waiting(False)
        self.returncode = self.proc.returncode
        return self.returncode

    # -- talking to it --------------------------------------------------

    def send(self, text: str) -> bool:
        """Type a line into the running command. True if it got there."""
        with self._lock:
            proc = self.proc
            stream = proc.stdin if proc is not None else None
        if stream is None or stream.closed:
            return False
        if not text.endswith("\n"):
            text += "\n"
        try:
            stream.write(text)
            stream.flush()
        except (BrokenPipeError, ValueError, OSError):
            return False
        self._typed = True
        self._set_waiting(False)
        return True

    def eof(self) -> bool:
        """Close its input, the way Ctrl-D does in a terminal."""
        with self._lock:
            proc = self.proc
            stream = proc.stdin if proc is not None else None
        if stream is None or stream.closed:
            return False
        try:
            stream.close()
        except (BrokenPipeError, ValueError, OSError):
            pass
        self._set_waiting(False)
        return True

    def _set_waiting(self, waiting: bool) -> None:
        if waiting == self.waiting:
            return
        self.waiting = waiting
        if self.on_waiting:
            try:
                self.on_waiting(waiting)
            except Exception:                                  # noqa: BLE001
                pass

    #: How long a command may sit waiting for an answer nobody types before its
    #: input is closed for it. Without this a forgotten prompt would hold a run
    #: open for ever; with it the run fails the way it always used to, just a
    #: couple of minutes later and after saying so on screen.
    INPUT_TIMEOUT = 180.0

    #: Only counts once the command has actually blocked on our pipe, so a
    #: quiet mdrun is never touched.
    INPUT_POLL = 2.0

    #: How long it has to stay blocked before it is called a question. Several
    #: programs read their input once as they start -- conda's activation and
    #: a couple of the Python tools do -- and announcing that as "waiting for
    #: an answer" sent people to the terminal drawer looking for a prompt that
    #: was never there. A real prompt sits still and is reported a few seconds
    #: later, which is nothing against the three minutes before its input is
    #: closed for it.
    WAITING_GRACE = 6.0

    def _group_pids(self) -> List[Tuple[int, str]]:
        """Every process in this step's group, as (pid, state letter)."""
        if self.pgid is None:
            return []
        found: List[Tuple[int, str]] = []
        try:
            names = os.listdir("/proc")
        except OSError:
            return []
        for name in names:
            if not name.isdigit():
                continue
            try:
                with open(f"/proc/{name}/stat", "rb") as fh:
                    fields = fh.read().rsplit(b")", 1)[-1].split()
                # after "comm)" the fields are state, ppid, pgrp, ...
                if int(fields[2]) == self.pgid:
                    found.append((int(name), fields[0].decode()))
            except (OSError, IndexError, ValueError):
                continue
        return found

    def _live_pids(self) -> List[int]:
        """The ones still doing something -- a reaped-but-unwaited leader is
        stuck in the list as a zombie and does not count as alive."""
        return [pid for pid, state in self._group_pids() if state != "Z"]

    def _blocked_on_our_input(self) -> bool:
        """Is some command in this step sitting on a read of our stdin pipe?"""
        if self._stdin_ino is None:
            return False
        want = f"pipe:[{self._stdin_ino}]"
        for pid, _state in self._group_pids():
            try:
                if os.readlink(f"/proc/{pid}/fd/0") != want:
                    continue
                with open(f"/proc/{pid}/wchan") as fh:
                    if "pipe_read" in fh.read():
                        return True
            except OSError:
                continue
        return False

    def _watch_input(self) -> None:
        """Notice a command asking a question, and do not wait for ever.

        Everything here is a best effort on top of /proc: on a system where it
        does not work the loop simply never fires, and a step that blocks on
        input behaves the way it did before -- except that the terminal drawer
        can still rescue it by hand.
        """
        blocked_since: Optional[float] = None
        while True:
            proc = self.proc
            if proc is None or proc.poll() is not None:
                return
            try:
                blocked = self._blocked_on_our_input()
            except Exception:                                  # noqa: BLE001
                return
            now = time.monotonic()
            if blocked:
                if blocked_since is None:
                    blocked_since = now
                if now - blocked_since >= self.WAITING_GRACE:
                    self._set_waiting(True)
                if (self.INPUT_TIMEOUT > 0 and not self._typed
                        and now - blocked_since > self.INPUT_TIMEOUT):
                    self.on_line("!! nothing was typed in "
                                 f"{int(self.INPUT_TIMEOUT)}s -- closing its input")
                    self.eof()
                    return
            else:
                blocked_since = None
                self._set_waiting(False)
            time.sleep(self.INPUT_POLL)

    def _pump(self, stream) -> None:
        """Forward the script's output, telling redraws apart from new lines.

        ``newline=""`` keeps the line terminator, which is the only way to know
        which is which: a chunk ending in CR is a progress bar repainting
        itself, and one ending in LF is a line that happened. Redraws are
        throttled, and the last one is always flushed before the next real
        line, so what is on screen is what the tool last said.
        """
        raw_stream = getattr(stream, "buffer", stream)
        wrapped = io.TextIOWrapper(raw_stream, encoding="utf-8", errors="replace",
                                   newline="")
        pending: Optional[str] = None
        last = 0.0

        def flush() -> None:
            nonlocal pending
            if pending is not None:
                (self.on_progress or self.on_line)(clean_output(pending))
                pending = None

        for raw in wrapped:
            if raw.endswith("\r"):                 # a redraw, not a new line
                pending = raw.rstrip("\r")
                now = time.monotonic()
                if now - last >= self.PROGRESS_INTERVAL:
                    last = now
                    flush()
                continue
            flush()
            line = clean_output(raw.rstrip("\r\n"))
            marker = _MARKER_RE.match(line.strip())
            if marker and self.on_step:
                kind, index, rc = marker.group(1), int(marker.group(2)), marker.group(3)
                self.on_step(kind, index, int(rc) if rc is not None else None)
                continue
            if marker:
                continue
            self.on_line(line)
        flush()

    # -- stopping it ----------------------------------------------------

    #: How long the polite signals get before the next one. INT first because
    #: that is what Ctrl-C sends and what mdrun listens for -- it finishes the
    #: step it is on, writes a checkpoint and stops, so the run can be picked
    #: up again later. TERM and KILL are for everything that ignores it.
    SOFT_GRACE = 4.0

    def _signal_group(self, sig: int) -> bool:
        """Signal every process of this step. True if there was one to signal.

        The group, never just the process we started: the generated script runs
        each step inside `( ... )`, which is a second process, and a `trap` in
        the user's own script can make the outer bash die while that subshell
        carries on holding the machine. That is exactly how a cancelled run
        used to leave work running -- the outer bash exited, so the old code
        saw a finished process and never sent the kill.
        """
        pgid = self.pgid
        if pgid is None:
            proc = self.proc
            if proc is None:
                return False
            pgid = proc.pid
        try:
            os.killpg(pgid, sig)
            return True
        except (ProcessLookupError, PermissionError, OSError):
            proc = self.proc
            if proc is None or proc.poll() is not None:
                return False
            try:
                proc.send_signal(sig)
                return True
            except (ProcessLookupError, OSError):
                return False

    def _settle(self, seconds: float) -> bool:
        """Wait a little for the group to empty. True if it did."""
        deadline = time.monotonic() + seconds
        while time.monotonic() < deadline:
            if not self._live_pids():
                return True
            time.sleep(0.15)
        return not self._live_pids()

    def cancel(self, grace: float = 5.0, hard: bool = False) -> None:
        """Stop this step. Ask nicely the first time, insist after that.

        Asking twice is the point: the second press of Cancel (or a second
        Ctrl-C in the terminal) goes straight to a kill nothing can ignore,
        which is what people expect from a terminal and what this did not do.
        """
        with self._lock:
            self._cancelled = True
            self._stops += 1
            insist = hard or self._stops > 1
            proc = self.proc
        if proc is None:
            return
        # Anything sitting on a prompt should see the door close too.
        self.eof()
        if insist:
            self._signal_group(signal.SIGKILL)
            return
        if not self._signal_group(signal.SIGINT):
            return
        if self._settle(self.SOFT_GRACE):
            return
        self._signal_group(signal.SIGTERM)
        if self._settle(grace):
            return
        self._signal_group(signal.SIGKILL)
