"""MDP presets and rendering.

Presets are plain ``{option: value}`` dictionaries so a node can start from one
and then override individual keys from its widgets.  :func:`render_mdp` writes
them back out grouped under section headers, which makes a generated file
readable enough to hand to a collaborator.
"""

from __future__ import annotations

from typing import Dict, Iterable, List, Tuple

# Section headers and the option order inside them.  Anything not listed here is
# appended under "other" in insertion order, so unknown options are never lost.
SECTIONS: List[Tuple[str, List[str]]] = [
    ("Run control", [
        "title", "integrator", "dt", "nsteps", "tinit", "init-step", "comm-mode", "nstcomm",
        "comm-grps", "emtol", "emstep", "nstcgsteep", "ld-seed", "bd-fric",
    ]),
    ("Output control", [
        "nstxout", "nstvout", "nstfout", "nstlog", "nstcalcenergy", "nstenergy",
        "nstxout-compressed",
        "compressed-x-precision", "compressed-x-grps", "energygrps",
    ]),
    ("Neighbour searching", [
        "cutoff-scheme", "nstlist", "ns-type", "pbc", "verlet-buffer-tolerance", "rlist",
    ]),
    ("Electrostatics", [
        "coulombtype", "coulomb-modifier", "rcoulomb", "rcoulomb-switch",
        "epsilon-r", "epsilon-rf", "fourierspacing", "pme-order", "ewald-rtol",
    ]),
    ("Van der Waals", [
        "vdwtype", "vdw-modifier", "rvdw", "rvdw-switch", "dispcorr",
    ]),
    ("Temperature coupling", [
        "tcoupl", "nsttcouple", "tc-grps", "tau-t", "ref-t",
    ]),
    ("Heating and cooling", [
        "annealing", "annealing-npoints", "annealing-time", "annealing-temp",
    ]),
    ("Pressure coupling", [
        "pcoupl", "pcoupltype", "nstpcouple", "tau-p", "compressibility", "ref-p",
        "refcoord-scaling",
    ]),
    ("Velocity generation", [
        "gen-vel", "gen-temp", "gen-seed",
    ]),
    ("Bonds", [
        "constraints", "constraint-algorithm", "continuation", "lincs-order",
        "lincs-iter", "lincs-warnangle", "mass-repartition-factor",
    ]),
    ("Restraints / pulling", [
        "define", "freezegrps", "freezedim", "pull", "pull-ngroups", "pull-ncoords",
    ]),
]

_CANONICAL = {key for _, keys in SECTIONS for key in keys}

#: GROMACS compares mdp option names with the separators removed entirely, so
#: ``vdw_type``, ``vdw-type`` and ``vdwtype`` are one option. Mapping a key back
#: to the spelling used in SECTIONS is what keeps a hand-written file from
#: landing half of its options under "other" when it is read and rewritten.
_BY_SQUASHED = {key.replace("-", ""): key for key in _CANONICAL}


def _norm(key: str) -> str:
    """GROMACS treats ``-`` and ``_`` in mdp keys as identical; we prefer ``-``."""
    key = key.strip().lower().replace("_", "-")
    return _BY_SQUASHED.get(key.replace("-", ""), key)


def render_mdp(options: Dict[str, object], title: str = "") -> str:
    normalised = {}
    for key, value in options.items():
        if value is None:
            continue
        normalised[_norm(key)] = value

    lines: List[str] = []
    if title:
        lines += [f"; {title}", "; generated by Comfy-gmx", ""]

    used = set()
    for section, keys in SECTIONS:
        present = [k for k in keys if k in normalised]
        if not present:
            continue
        lines.append(f"; ---- {section} " + "-" * max(0, 48 - len(section)))
        width = max(len(k) for k in present)
        for key in present:
            lines.append(f"{key.ljust(width)} = {normalised[key]}")
            used.add(key)
        lines.append("")

    leftover = [k for k in normalised if k not in used]
    if leftover:
        lines.append("; ---- Other " + "-" * 48)
        width = max(len(k) for k in leftover)
        for key in leftover:
            lines.append(f"{key.ljust(width)} = {normalised[key]}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_mdp(text: str) -> Dict[str, str]:
    """Read an mdp file into a dict, dropping comments."""
    out: Dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.split(";", 1)[0].strip()
        if not line or "=" not in line:
            continue
        key, value = line.split("=", 1)
        out[_norm(key)] = value.strip()
    return out


def merge_extra(options: Dict[str, object], extra_text: str) -> Dict[str, object]:
    """Overlay free-text ``key = value`` lines on top of a preset."""
    merged = dict(options)
    merged.update(parse_mdp(extra_text or ""))
    return merged


# --------------------------------------------------------------------------
# Building blocks
# --------------------------------------------------------------------------

_OUTPUT_SPARSE = {
    "nstxout": 0,
    "nstvout": 0,
    "nstfout": 0,
    "nstlog": 1000,
    "nstenergy": 1000,
    "nstxout-compressed": 1000,
    "compressed-x-precision": 1000,
}

_ATOMISTIC_NONBONDED = {
    "cutoff-scheme": "Verlet",
    "nstlist": 20,
    "pbc": "xyz",
    "verlet-buffer-tolerance": 0.005,
    "coulombtype": "PME",
    "rcoulomb": 1.2,
    "fourierspacing": 0.12,
    "pme-order": 4,
    "vdwtype": "cutoff",
    "vdw-modifier": "force-switch",
    "rvdw-switch": 1.0,
    "rvdw": 1.2,
    "dispcorr": "no",
}

def _preset(*dicts: Dict[str, object]) -> Dict[str, object]:
    out: Dict[str, object] = {}
    for d in dicts:
        out.update(d)
    return out


PRESETS: Dict[str, Dict[str, object]] = {
    "em_atomistic": _preset(
        {"integrator": "steep", "emtol": 1000.0, "emstep": 0.01, "nsteps": 50000},
        _ATOMISTIC_NONBONDED,
        {"nstlog": 100, "nstenergy": 100, "constraints": "none"},
    ),
    "nvt_atomistic": _preset(
        {"integrator": "md", "dt": 0.002, "nsteps": 50000, "comm-mode": "Linear", "nstcomm": 100},
        _ATOMISTIC_NONBONDED,
        _OUTPUT_SPARSE,
        {
            "tcoupl": "V-rescale", "tc-grps": "Protein Non-Protein",
            "tau-t": "0.1 0.1", "ref-t": "310 310",
            "pcoupl": "no",
            "gen-vel": "yes", "gen-temp": 310, "gen-seed": -1,
            "constraints": "h-bonds", "constraint-algorithm": "lincs",
            "continuation": "no", "lincs-order": 4, "lincs-iter": 1,
            "define": "-DPOSRES",
        },
    ),
    "npt_atomistic": _preset(
        {"integrator": "md", "dt": 0.002, "nsteps": 50000, "comm-mode": "Linear", "nstcomm": 100},
        _ATOMISTIC_NONBONDED,
        _OUTPUT_SPARSE,
        {
            "tcoupl": "V-rescale", "tc-grps": "Protein Non-Protein",
            "tau-t": "0.1 0.1", "ref-t": "310 310",
            "pcoupl": "C-rescale", "pcoupltype": "isotropic",
            "tau-p": 5.0, "compressibility": "4.5e-5", "ref-p": 1.0,
            "refcoord-scaling": "com",
            "gen-vel": "no",
            "constraints": "h-bonds", "constraint-algorithm": "lincs",
            "continuation": "yes", "lincs-order": 4, "lincs-iter": 1,
            "define": "-DPOSRES",
        },
    ),
    "md_atomistic": _preset(
        {"integrator": "md", "dt": 0.002, "nsteps": 50000000, "comm-mode": "Linear", "nstcomm": 100},
        _ATOMISTIC_NONBONDED,
        {
            "nstxout": 0, "nstvout": 0, "nstfout": 0,
            "nstlog": 5000, "nstenergy": 5000,
            "nstxout-compressed": 5000, "compressed-x-precision": 1000,
        },
        {
            "tcoupl": "V-rescale", "tc-grps": "Protein Non-Protein",
            "tau-t": "0.1 0.1", "ref-t": "310 310",
            "pcoupl": "Parrinello-Rahman", "pcoupltype": "isotropic",
            "tau-p": 5.0, "compressibility": "4.5e-5", "ref-p": 1.0,
            "gen-vel": "no",
            "constraints": "h-bonds", "constraint-algorithm": "lincs",
            "continuation": "yes",
        },
    ),
}

# --------------------------------------------------------------------------
# Tutorial presets
#
# Transcribed verbatim from the "Lysozyme in Water" tutorial by Justin A.
# Lemkul (http://www.mdtutorials.com/gmx/lysozyme/), 2025.x edition. They are
# kept exactly as published -- including the CHARMM36 nonbonded settings, the
# 298 K reference temperature and the C-rescale barostat -- so that a run
# through Comfy-gmx reproduces the tutorial's numbers rather than approximating
# them. Reference copies are written to comfygmx/mdp/.
# --------------------------------------------------------------------------

_LYS_EM = {
    "integrator": "steep",
    "emtol": 1000.0,
    "emstep": 0.01,
    "nsteps": 50000,
    "nstlist": 1,
    "cutoff-scheme": "Verlet",
    "ns-type": "grid",
    "rcoulomb": 1.0,
    "rvdw": 1.0,
    "pbc": "xyz",
}

# CHARMM36 nonbonded settings, identical across the three dynamics stages.
_LYS_NONBONDED = {
    "cutoff-scheme": "Verlet",
    "ns-type": "grid",
    "nstlist": 10,
    "rvdw": 1.2,
    "rvdw-switch": 1.0,
    "vdw-modifier": "force-switch",
    "dispcorr": "No",
    "rcoulomb": 1.2,
    "coulombtype": "PME",
    "pme-order": 4,
    "fourierspacing": 0.16,
    "pbc": "xyz",
}

_LYS_BONDS = {
    "constraint-algorithm": "lincs",
    "constraints": "h-bonds",
    "lincs-iter": 1,
    "lincs-order": 4,
}

_LYS_TCOUPL = {
    "tcoupl": "V-rescale",
    "tc-grps": "System",
    "tau-t": 1.0,
    "ref-t": 298,
}

_LYS_PCOUPL = {
    "pcoupl": "C-rescale",
    "pcoupltype": "isotropic",
    "tau-p": 5.0,
    "ref-p": 1.0,
    "compressibility": "4.5e-5",
}

PRESETS.update({
    "lysozyme_ions": _preset(_LYS_EM, {"coulombtype": "cutoff"}),
    "lysozyme_min": _preset(_LYS_EM, {"coulombtype": "PME"}),
    "lysozyme_nvt": _preset(
        {"title": "Lysozyme NVT equilibration", "define": "-DPOSRES",
         "integrator": "md", "nsteps": 50000, "dt": 0.002,
         "nstxout": 2500, "nstvout": 2500, "nstenergy": 2500, "nstlog": 2500,
         "continuation": "no"},
        _LYS_BONDS, _LYS_NONBONDED, _LYS_TCOUPL,
        {"pcoupl": "no", "gen-vel": "yes", "gen-temp": 298, "gen-seed": -1},
    ),
    "lysozyme_npt": _preset(
        {"title": "Lysozyme NPT equilibration", "define": "-DPOSRES",
         "integrator": "md", "nsteps": 250000, "dt": 0.002,
         "nstxout": 500, "nstvout": 500, "nstenergy": 500, "nstlog": 500,
         "continuation": "yes"},
        _LYS_BONDS, _LYS_NONBONDED, _LYS_TCOUPL, _LYS_PCOUPL,
        {"refcoord-scaling": "com", "gen-vel": "no"},
    ),
    "lysozyme_md": _preset(
        {"title": "Lysozyme production MD",
         "integrator": "md", "nsteps": 5000000, "dt": 0.002,
         "nstxout": 0, "nstvout": 0, "nstfout": 0,
         "nstenergy": 5000, "nstlog": 5000,
         "nstxout-compressed": 5000, "compressed-x-grps": "System",
         "continuation": "yes"},
        _LYS_BONDS, _LYS_NONBONDED, _LYS_TCOUPL, _LYS_PCOUPL,
        {"gen-vel": "no"},
    ),
})


PRESET_INFO: Dict[str, str] = {
    "em_atomistic": "Steepest-descent minimisation, PME, force-switched LJ (CHARMM36-style).",
    "nvt_atomistic": "NVT equilibration with position restraints and velocity generation.",
    "npt_atomistic": "NPT equilibration, C-rescale barostat, restraints still on.",
    "md_atomistic": "Unrestrained production MD, Parrinello-Rahman.",
    # The tutorial's own five, in plain words: the first line of every file
    # written from them, and the note on the block, which a newcomer reads.
    "lysozyme_ions": "Lysozyme tutorial, as published. Nothing runs with these "
                     "settings: they only build the run file that genion needs "
                     "to place the ions.",
    "lysozyme_min": "Lysozyme tutorial, as published. Energy minimisation: moves "
                    "the atoms until the strongest force on any atom is below "
                    "1000 kJ/mol/nm.",
    "lysozyme_nvt": "Lysozyme tutorial, as published. 100 ps at 298 K in a box "
                    "of fixed size: new random speeds at the start, the protein "
                    "held in place by springs.",
    "lysozyme_npt": "Lysozyme tutorial, as published. 500 ps at 298 K and 1 bar: "
                    "the box may shrink or grow, the protein is still held by "
                    "springs.",
    "lysozyme_md": "Lysozyme tutorial, as published. 10 ns at 298 K and 1 bar, "
                   "with nothing holding the protein.",
}


def preset_names() -> Iterable[str]:
    return PRESETS.keys()
