"""MDP presets and rendering.

Presets are plain ``{option: value}`` dictionaries so a node can start from one
and then override individual keys from its widgets.  :func:`render_mdp` writes
them back out grouped under section headers, which makes a generated file
readable enough to hand to a collaborator.
"""

from __future__ import annotations

from typing import Dict, Iterable, List, Tuple

# Section headers and the option order inside them.  Anything not listed here is
# appended under "other" in insertion order, so unknown options are never lost.
SECTIONS: List[Tuple[str, List[str]]] = [
    ("Run control", [
        "title", "integrator", "dt", "nsteps", "tinit", "init-step", "comm-mode", "nstcomm",
        "comm-grps", "emtol", "emstep", "nstcgsteep",
    ]),
    ("Output control", [
        "nstxout", "nstvout", "nstfout", "nstlog", "nstenergy", "nstxout-compressed",
        "compressed-x-precision", "compressed-x-grps", "energygrps",
    ]),
    ("Neighbour searching", [
        "cutoff-scheme", "nstlist", "ns-type", "pbc", "verlet-buffer-tolerance", "rlist",
    ]),
    ("Electrostatics", [
        "coulombtype", "coulomb-modifier", "rcoulomb", "rcoulomb-switch",
        "epsilon-r", "epsilon-rf", "fourierspacing", "pme-order", "ewald-rtol",
    ]),
    ("Van der Waals", [
        "vdwtype", "vdw-modifier", "rvdw", "rvdw-switch", "dispcorr",
    ]),
    ("Temperature coupling", [
        "tcoupl", "tc-grps", "tau-t", "ref-t",
    ]),
    ("Pressure coupling", [
        "pcoupl", "pcoupltype", "tau-p", "compressibility", "ref-p", "refcoord-scaling",
    ]),
    ("Velocity generation", [
        "gen-vel", "gen-temp", "gen-seed",
    ]),
    ("Bonds", [
        "constraints", "constraint-algorithm", "continuation", "lincs-order",
        "lincs-iter", "lincs-warnangle",
    ]),
    ("Restraints / pulling", [
        "define", "freezegrps", "freezedim", "pull", "pull-ngroups", "pull-ncoords",
    ]),
]

_CANONICAL = {key for _, keys in SECTIONS for key in keys}

#: GROMACS compares mdp option names with the separators removed entirely, so
#: ``vdw_type``, ``vdw-type`` and ``vdwtype`` are one option. Mapping a key back
#: to the spelling used in SECTIONS is what keeps a hand-written file from
#: landing half of its options under "other" when it is read and rewritten.
_BY_SQUASHED = {key.replace("-", ""): key for key in _CANONICAL}


def _norm(key: str) -> str:
    """GROMACS treats ``-`` and ``_`` in mdp keys as identical; we prefer ``-``."""
    key = key.strip().lower().replace("_", "-")
    return _BY_SQUASHED.get(key.replace("-", ""), key)


def render_mdp(options: Dict[str, object], title: str = "") -> str:
    normalised = {}
    for key, value in options.items():
        if value is None:
            continue
        normalised[_norm(key)] = value

    lines: List[str] = []
    if title:
        lines += [f"; {title}", "; generated by Comfy-gmx", ""]

    used = set()
    for section, keys in SECTIONS:
        present = [k for k in keys if k in normalised]
        if not present:
            continue
        lines.append(f"; ---- {section} " + "-" * max(0, 48 - len(section)))
        width = max(len(k) for k in present)
        for key in present:
            lines.append(f"{key.ljust(width)} = {normalised[key]}")
            used.add(key)
        lines.append("")

    leftover = [k for k in normalised if k not in used]
    if leftover:
        lines.append("; ---- Other " + "-" * 48)
        width = max(len(k) for k in leftover)
        for key in leftover:
            lines.append(f"{key.ljust(width)} = {normalised[key]}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_mdp(text: str) -> Dict[str, str]:
    """Read an mdp file into a dict, dropping comments."""
    out: Dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.split(";", 1)[0].strip()
        if not line or "=" not in line:
            continue
        key, value = line.split("=", 1)
        out[_norm(key)] = value.strip()
    return out


def merge_extra(options: Dict[str, object], extra_text: str) -> Dict[str, object]:
    """Overlay free-text ``key = value`` lines on top of a preset."""
    merged = dict(options)
    merged.update(parse_mdp(extra_text or ""))
    return merged


# --------------------------------------------------------------------------
# Building blocks
# --------------------------------------------------------------------------

_OUTPUT_SPARSE = {
    "nstxout": 0,
    "nstvout": 0,
    "nstfout": 0,
    "nstlog": 1000,
    "nstenergy": 1000,
    "nstxout-compressed": 1000,
    "compressed-x-precision": 1000,
}

_ATOMISTIC_NONBONDED = {
    "cutoff-scheme": "Verlet",
    "nstlist": 20,
    "pbc": "xyz",
    "verlet-buffer-tolerance": 0.005,
    "coulombtype": "PME",
    "rcoulomb": 1.2,
    "fourierspacing": 0.12,
    "pme-order": 4,
    "vdwtype": "cutoff",
    "vdw-modifier": "force-switch",
    "rvdw-switch": 1.0,
    "rvdw": 1.2,
    "dispcorr": "no",
}

# Martini 3 production settings (Verlet + reaction field, de Jong 2016 /
# Souza 2021).  epsilon-r = 15 is what the force field is parameterised with.
_MARTINI_NONBONDED = {
    "cutoff-scheme": "Verlet",
    "nstlist": 20,
    "pbc": "xyz",
    "verlet-buffer-tolerance": 0.005,
    "coulombtype": "reaction-field",
    "coulomb-modifier": "Potential-shift-verlet",
    "rcoulomb": 1.1,
    "epsilon-r": 15,
    "epsilon-rf": 0,
    "vdwtype": "cutoff",
    "vdw-modifier": "Potential-shift-verlet",
    "rvdw": 1.1,
    "dispcorr": "no",
}


def _preset(*dicts: Dict[str, object]) -> Dict[str, object]:
    out: Dict[str, object] = {}
    for d in dicts:
        out.update(d)
    return out


PRESETS: Dict[str, Dict[str, object]] = {
    "em_atomistic": _preset(
        {"integrator": "steep", "emtol": 1000.0, "emstep": 0.01, "nsteps": 50000},
        _ATOMISTIC_NONBONDED,
        {"nstlog": 100, "nstenergy": 100, "constraints": "none"},
    ),
    "nvt_atomistic": _preset(
        {"integrator": "md", "dt": 0.002, "nsteps": 50000, "comm-mode": "Linear", "nstcomm": 100},
        _ATOMISTIC_NONBONDED,
        _OUTPUT_SPARSE,
        {
            "tcoupl": "V-rescale", "tc-grps": "Protein Non-Protein",
            "tau-t": "0.1 0.1", "ref-t": "310 310",
            "pcoupl": "no",
            "gen-vel": "yes", "gen-temp": 310, "gen-seed": -1,
            "constraints": "h-bonds", "constraint-algorithm": "lincs",
            "continuation": "no", "lincs-order": 4, "lincs-iter": 1,
            "define": "-DPOSRES",
        },
    ),
    "npt_atomistic": _preset(
        {"integrator": "md", "dt": 0.002, "nsteps": 50000, "comm-mode": "Linear", "nstcomm": 100},
        _ATOMISTIC_NONBONDED,
        _OUTPUT_SPARSE,
        {
            "tcoupl": "V-rescale", "tc-grps": "Protein Non-Protein",
            "tau-t": "0.1 0.1", "ref-t": "310 310",
            "pcoupl": "C-rescale", "pcoupltype": "isotropic",
            "tau-p": 5.0, "compressibility": "4.5e-5", "ref-p": 1.0,
            "refcoord-scaling": "com",
            "gen-vel": "no",
            "constraints": "h-bonds", "constraint-algorithm": "lincs",
            "continuation": "yes", "lincs-order": 4, "lincs-iter": 1,
            "define": "-DPOSRES",
        },
    ),
    "md_atomistic": _preset(
        {"integrator": "md", "dt": 0.002, "nsteps": 50000000, "comm-mode": "Linear", "nstcomm": 100},
        _ATOMISTIC_NONBONDED,
        {
            "nstxout": 0, "nstvout": 0, "nstfout": 0,
            "nstlog": 5000, "nstenergy": 5000,
            "nstxout-compressed": 5000, "compressed-x-precision": 1000,
        },
        {
            "tcoupl": "V-rescale", "tc-grps": "Protein Non-Protein",
            "tau-t": "0.1 0.1", "ref-t": "310 310",
            "pcoupl": "Parrinello-Rahman", "pcoupltype": "isotropic",
            "tau-p": 5.0, "compressibility": "4.5e-5", "ref-p": 1.0,
            "gen-vel": "no",
            "constraints": "h-bonds", "constraint-algorithm": "lincs",
            "continuation": "yes",
        },
    ),
    "em_martini": _preset(
        {"integrator": "steep", "emtol": 100.0, "emstep": 0.001, "nsteps": 10000},
        _MARTINI_NONBONDED,
        {"nstlog": 100, "nstenergy": 100, "constraints": "none"},
    ),
    "eq_martini": _preset(
        {"integrator": "md", "dt": 0.005, "nsteps": 200000, "comm-mode": "Linear", "nstcomm": 100},
        _MARTINI_NONBONDED,
        _OUTPUT_SPARSE,
        {
            "tcoupl": "V-rescale", "tc-grps": "PROTEIN MEMBRANE SOLVENT",
            "tau-t": "1.0 1.0 1.0", "ref-t": "310 310 310",
            "pcoupl": "C-rescale", "pcoupltype": "semiisotropic",
            "tau-p": 12.0, "compressibility": "3e-4 3e-4", "ref-p": "1.0 1.0",
            "refcoord-scaling": "all",
            "gen-vel": "yes", "gen-temp": 310, "gen-seed": -1,
            "constraints": "none", "constraint-algorithm": "Lincs",
            "continuation": "no", "lincs-order": 8, "lincs-warnangle": 90,
            "define": "-DPOSRES -DPOSRES_FC=1000",
        },
    ),
    "md_martini": _preset(
        {"integrator": "md", "dt": 0.020, "nsteps": 50000000, "comm-mode": "Linear", "nstcomm": 100},
        _MARTINI_NONBONDED,
        {
            "nstxout": 0, "nstvout": 0, "nstfout": 0,
            "nstlog": 10000, "nstenergy": 10000,
            "nstxout-compressed": 10000, "compressed-x-precision": 1000,
        },
        {
            "tcoupl": "V-rescale", "tc-grps": "PROTEIN MEMBRANE SOLVENT",
            "tau-t": "1.0 1.0 1.0", "ref-t": "310 310 310",
            "pcoupl": "Parrinello-Rahman", "pcoupltype": "semiisotropic",
            "tau-p": 12.0, "compressibility": "3e-4 3e-4", "ref-p": "1.0 1.0",
            "gen-vel": "no",
            "constraints": "none", "constraint-algorithm": "Lincs",
            "continuation": "yes", "lincs-order": 8, "lincs-warnangle": 90,
        },
    ),
}

# --------------------------------------------------------------------------
# Tutorial presets
#
# Transcribed verbatim from the "Lysozyme in Water" tutorial by Justin A.
# Lemkul (http://www.mdtutorials.com/gmx/lysozyme/), 2025.x edition. They are
# kept exactly as published -- including the CHARMM36 nonbonded settings, the
# 298 K reference temperature and the C-rescale barostat -- so that a run
# through Comfy-gmx reproduces the tutorial's numbers rather than approximating
# them. Reference copies are written to comfygmx/mdp/.
# --------------------------------------------------------------------------

_LYS_EM = {
    "integrator": "steep",
    "emtol": 1000.0,
    "emstep": 0.01,
    "nsteps": 50000,
    "nstlist": 1,
    "cutoff-scheme": "Verlet",
    "ns-type": "grid",
    "rcoulomb": 1.0,
    "rvdw": 1.0,
    "pbc": "xyz",
}

# CHARMM36 nonbonded settings, identical across the three dynamics stages.
_LYS_NONBONDED = {
    "cutoff-scheme": "Verlet",
    "ns-type": "grid",
    "nstlist": 10,
    "rvdw": 1.2,
    "rvdw-switch": 1.0,
    "vdw-modifier": "force-switch",
    "dispcorr": "No",
    "rcoulomb": 1.2,
    "coulombtype": "PME",
    "pme-order": 4,
    "fourierspacing": 0.16,
    "pbc": "xyz",
}

_LYS_BONDS = {
    "constraint-algorithm": "lincs",
    "constraints": "h-bonds",
    "lincs-iter": 1,
    "lincs-order": 4,
}

_LYS_TCOUPL = {
    "tcoupl": "V-rescale",
    "tc-grps": "System",
    "tau-t": 1.0,
    "ref-t": 298,
}

_LYS_PCOUPL = {
    "pcoupl": "C-rescale",
    "pcoupltype": "isotropic",
    "tau-p": 5.0,
    "ref-p": 1.0,
    "compressibility": "4.5e-5",
}

PRESETS.update({
    "lysozyme_ions": _preset(_LYS_EM, {"coulombtype": "cutoff"}),
    "lysozyme_min": _preset(_LYS_EM, {"coulombtype": "PME"}),
    "lysozyme_nvt": _preset(
        {"title": "Lysozyme NVT equilibration", "define": "-DPOSRES",
         "integrator": "md", "nsteps": 50000, "dt": 0.002,
         "nstxout": 2500, "nstvout": 2500, "nstenergy": 2500, "nstlog": 2500,
         "continuation": "no"},
        _LYS_BONDS, _LYS_NONBONDED, _LYS_TCOUPL,
        {"pcoupl": "no", "gen-vel": "yes", "gen-temp": 298, "gen-seed": -1},
    ),
    "lysozyme_npt": _preset(
        {"title": "Lysozyme NPT equilibration", "define": "-DPOSRES",
         "integrator": "md", "nsteps": 250000, "dt": 0.002,
         "nstxout": 500, "nstvout": 500, "nstenergy": 500, "nstlog": 500,
         "continuation": "yes"},
        _LYS_BONDS, _LYS_NONBONDED, _LYS_TCOUPL, _LYS_PCOUPL,
        {"refcoord-scaling": "com", "gen-vel": "no"},
    ),
    "lysozyme_md": _preset(
        {"title": "Lysozyme production MD",
         "integrator": "md", "nsteps": 5000000, "dt": 0.002,
         "nstxout": 0, "nstvout": 0, "nstfout": 0,
         "nstenergy": 5000, "nstlog": 5000,
         "nstxout-compressed": 5000, "compressed-x-grps": "System",
         "continuation": "yes"},
        _LYS_BONDS, _LYS_NONBONDED, _LYS_TCOUPL, _LYS_PCOUPL,
        {"gen-vel": "no"},
    ),
})


PRESET_INFO: Dict[str, str] = {
    "em_atomistic": "Steepest-descent minimisation, PME, force-switched LJ (CHARMM36-style).",
    "nvt_atomistic": "NVT equilibration with position restraints and velocity generation.",
    "npt_atomistic": "NPT equilibration, C-rescale barostat, restraints still on.",
    "md_atomistic": "Unrestrained production MD, Parrinello-Rahman.",
    "em_martini": "Martini 3 minimisation: reaction field, epsilon_r = 15, small emstep for freshly packed membranes.",
    "eq_martini": "Martini 3 equilibration: 5 fs steps, semiisotropic C-rescale, backbone restrained.",
    "md_martini": "Martini 3 production: 20 fs steps, semiisotropic Parrinello-Rahman.",
    "lysozyme_ions": "Lysozyme tutorial, verbatim: throwaway minimisation used only to "
                     "build the tpr genion needs (plain cutoff electrostatics).",
    "lysozyme_min": "Lysozyme tutorial, verbatim: steepest descent to Fmax < 1000, PME.",
    "lysozyme_nvt": "Lysozyme tutorial, verbatim: 100 ps restrained NVT at 298 K, "
                    "CHARMM36 force-switched LJ, velocities generated.",
    "lysozyme_npt": "Lysozyme tutorial, verbatim: 500 ps restrained NPT, C-rescale barostat.",
    "lysozyme_md": "Lysozyme tutorial, verbatim: 10 ns unrestrained production MD.",
}


# --------------------------------------------------------------------------
# Martini 3 tutorial presets
#
# The nonbonded block below is the one every Martini 3 tutorial ships: straight
# cutoffs at 1.1 nm with a reaction field and epsilon_r = 15. It is not a
# stylistic choice -- the Martini 3 parameters were fitted with it, so changing
# it changes the model.
#
# The KALP presets are transcribed from the .mdp files in the "Proteins II"
# tutorial archive (cgmartini.nl, KALP_ProteinsII_Tutorial.zip). The CK1d
# presets follow martini_v3.0_prod.mdp from the Martini download page, switched
# to isotropic pressure coupling because a protein in water has no membrane
# plane to couple separately.
# --------------------------------------------------------------------------

_M3_NONBONDED = {
    "cutoff-scheme": "Verlet",
    "nstlist": 20,
    "ns-type": "grid",
    "pbc": "xyz",
    "verlet-buffer-tolerance": 0.005,
    "coulombtype": "reaction-field",
    "rcoulomb": 1.1,
    "epsilon-r": 15,
    "epsilon-rf": 0,
    "vdwtype": "cutoff",
    "vdw-modifier": "Potential-shift-verlet",
    "rvdw": 1.1,
}

# Production runs disable the Verlet buffer estimate and set rlist by hand:
# with a 20 fs step the estimator picks a buffer that lets membrane undulations
# grow. rlist >= 1.35 nm is the tutorial's number for nstlist = 20.
_M3_NONBONDED_PROD = dict(_M3_NONBONDED)
_M3_NONBONDED_PROD.update({"verlet-buffer-tolerance": -1, "rlist": 1.35})

_M3_OUTPUT = {
    "nstxout": 0,
    "nstvout": 0,
    "nstfout": 0,
    "nstlog": 1000,
    "nstxout-compressed": 1000,
    "compressed-x-precision": 100,
}

PRESETS.update({
    # ---- KALP in a POPC bilayer, Proteins II -----------------------------
    "martini3_kalp_min": _preset(
        {"integrator": "steep", "nsteps": 1000, "nstxout": 0, "nstfout": 0,
         "nstlog": 100},
        _M3_NONBONDED,
    ),
    "martini3_kalp_eq": _preset(
        {"define": "-DPOSRES", "integrator": "md", "dt": 0.01, "nsteps": 100000},
        _M3_OUTPUT,
        _M3_NONBONDED,
        {
            "tcoupl": "v-rescale", "tc-grps": "Protein_POPC W_ION",
            "tau-t": "1.0 1.0", "ref-t": "300 300",
            "gen-vel": "yes", "gen-temp": 300,
            "pcoupl": "c-rescale", "pcoupltype": "semiisotropic",
            "tau-p": 4.0, "compressibility": "4.5e-5 4.5e-5", "ref-p": "1.0 1.0",
            "refcoord-scaling": "com",
        },
    ),
    "martini3_kalp_md": _preset(
        {"integrator": "md", "dt": 0.02, "nsteps": 1000000},
        _M3_OUTPUT,
        _M3_NONBONDED_PROD,
        {
            "tcoupl": "v-rescale", "tc-grps": "Protein_POPC W_ION",
            "tau-t": "1.0 1.0", "ref-t": "300 300",
            "continuation": "yes", "gen-vel": "no",
            "pcoupl": "parrinello-rahman", "pcoupltype": "semiisotropic",
            "tau-p": 12.0, "compressibility": "3e-4 3e-4", "ref-p": "1.0 1.0",
            "lincs-order": 4, "lincs-warnangle": 30,
        },
    ),

    # ---- the self-assembly route -----------------------------------------
    # No bilayer exists yet, so there is no plane to couple to and no
    # Protein_POPC / W_ION index: pressure is isotropic and the whole system is
    # one temperature group until the membrane has formed.
    "martini3_kalp_sa_min": _preset(
        {"integrator": "steep", "nsteps": 2000, "nstxout": 0, "nstfout": 0,
         "nstlog": 100, "define": "-DPOSRES -DFLEXIBLE"},
        _M3_NONBONDED,
    ),
    "martini3_kalp_sa_eq": _preset(
        {"define": "-DPOSRES", "integrator": "md", "dt": 0.01, "nsteps": 100000,
         "comm-mode": "Linear", "nstcomm": 100},
        _M3_OUTPUT,
        _M3_NONBONDED,
        {
            "tcoupl": "v-rescale", "tc-grps": "System",
            "tau-t": 1.0, "ref-t": 300,
            "gen-vel": "yes", "gen-temp": 300,
            "pcoupl": "c-rescale", "pcoupltype": "isotropic",
            "tau-p": 6.0, "compressibility": "3e-4", "ref-p": 1.0,
            "refcoord-scaling": "com",
        },
    ),
    "martini3_kalp_sa_md": _preset(
        {"title": "KALP self-assembly", "integrator": "md", "dt": 0.02,
         "nsteps": 1000000, "comm-mode": "Linear", "nstcomm": 100},
        _M3_OUTPUT,
        _M3_NONBONDED_PROD,
        {
            "tcoupl": "v-rescale", "tc-grps": "System", "tau-t": 1.0, "ref-t": 300,
            "continuation": "yes", "gen-vel": "no",
            "pcoupl": "parrinello-rahman", "pcoupltype": "isotropic",
            "tau-p": 12.0, "compressibility": "3e-4", "ref-p": 1.0,
            "constraints": "none", "constraint-algorithm": "Lincs",
            "lincs-order": 4, "lincs-warnangle": 30,
        },
    ),

    # ---- CK1d in water, Proteins I ---------------------------------------
    "martini3_sol_min": _preset(
        {"integrator": "steep", "nsteps": 5000, "emtol": 100.0, "emstep": 0.001,
         "nstxout": 0, "nstfout": 0, "nstlog": 100},
        _M3_NONBONDED,
    ),
    "martini3_sol_eq": _preset(
        {"define": "-DPOSRES", "integrator": "md", "dt": 0.01, "nsteps": 100000,
         "comm-mode": "Linear", "nstcomm": 100},
        _M3_OUTPUT,
        _M3_NONBONDED,
        {
            "tcoupl": "v-rescale", "tc-grps": "Protein Non-Protein",
            "tau-t": "1.0 1.0", "ref-t": "310 310",
            "gen-vel": "yes", "gen-temp": 310, "gen-seed": -1,
            "pcoupl": "c-rescale", "pcoupltype": "isotropic",
            "tau-p": 4.0, "compressibility": "3e-4", "ref-p": 1.0,
            "refcoord-scaling": "all",
        },
    ),
    "martini3_sol_md": _preset(
        {"integrator": "md", "dt": 0.02, "nsteps": 12500000,
         "comm-mode": "Linear", "nstcomm": 100},
        {"nstxout": 0, "nstvout": 0, "nstfout": 0,
         "nstlog": 25000, "nstenergy": 25000,
         "nstxout-compressed": 25000, "compressed-x-precision": 100},
        _M3_NONBONDED_PROD,
        {
            "nsttcouple": 20, "nstpcouple": 20,
            "tcoupl": "v-rescale", "tc-grps": "Protein Non-Protein",
            "tau-t": "1.0 1.0", "ref-t": "310 310",
            "continuation": "yes", "gen-vel": "no",
            "pcoupl": "parrinello-rahman", "pcoupltype": "isotropic",
            "tau-p": 12.0, "compressibility": "3e-4", "ref-p": 1.0,
            "constraints": "none", "constraint-algorithm": "Lincs",
            "lincs-order": 8, "lincs-warnangle": 90, "lincs-iter": 2,
        },
    ),
})

PRESET_INFO.update({
    "martini3_kalp_min": "Proteins II, verbatim: 1000 steps of steepest descent on a "
                         "pre-built bilayer.",
    "martini3_kalp_eq": "Proteins II, verbatim: 1 ns restrained equilibration, 10 fs "
                        "steps, semiisotropic c-rescale, needs a Protein_POPC / W_ION index.",
    "martini3_kalp_md": "Proteins II, verbatim: 20 ns production at 20 fs, semiisotropic "
                        "Parrinello-Rahman, needs a Protein_POPC / W_ION index.",
    "martini3_kalp_sa_min": "Proteins II self-assembly: 2000 steps with flexible bonds, "
                            "for a box of randomly placed lipids.",
    "martini3_kalp_sa_eq": "Proteins II self-assembly: isotropic coupling and one "
                           "temperature group -- there is no bilayer plane yet.",
    "martini3_kalp_sa_md": "Proteins II self-assembly: 20 ns isotropic production; the "
                           "bilayer forms within the first few nanoseconds.",
    "martini3_sol_min": "Proteins I: steepest descent for a Martini protein in water.",
    "martini3_sol_eq": "Proteins I: 1 ns restrained isotropic NPT at 310 K.",
    "martini3_sol_md": "Proteins I: 250 ns production, isotropic Parrinello-Rahman. "
                       "That is roughly 1 us of effective time at Martini's 1:4 ratio.",
})


def preset_names() -> Iterable[str]:
    return PRESETS.keys()
