#!/usr/bin/env python3
"""Regenerate docs/nodes.md from the live node registry.

Run after adding or changing a node:  python3 tools/generate_docs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from comfygmx.chunks import CHUNKS            # noqa: E402
from comfygmx.registry import REGISTRY        # noqa: E402
from comfygmx.templates import PRESETS, PRESET_INFO  # noqa: E402


def escape(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def main() -> int:
    lines = [
        "# Node reference",
        "",
        "Generated by `tools/generate_docs.py`; do not edit by hand.",
        "",
        f"{len(REGISTRY.specs())} node types in {len(REGISTRY.categories())} categories.",
        "",
        "Every node also carries parameters that are not listed below:",
        "",
        "- **Extra flags** — appended verbatim to the command that node runs, so an "
        "option Comfy-gmx does not model is never a dead end. The box names that "
        "command, and in the editor it carries the command's own flag list with a "
        "one-line definition each, taken from its help output by "
        "`tools/harvest_flags.py`. A node with no single command to append to — one "
        "that copies a file or draws a picture — has no such box. On the "
        "run-parameters node the same box takes raw `key = value` mdp lines instead.",
        "- **Conda env override** — run this one node inside a different environment "
        "than the one registered for its tool.",
        "",
        "Every node also has a step-by-step panel, reached from the gear on its "
        "header or from its right-click menu. It is the same boxes with room "
        "around them: each explanation is on screen instead of in a tooltip, "
        "nothing is hidden behind a triangle, what is plugged into each input is "
        "listed, and the command that will run sits at the bottom and changes as "
        "the boxes do. Boxes marked below as having a fill-in-the-blanks form get "
        "a button there and on the node itself, which asks for that box's contents "
        "with dropdowns and numbers instead.",
        "",
        "## Contents",
        "",
    ]
    for category in REGISTRY.categories():
        anchor = category["name"].lower().replace(" ", "-").replace("/", "").replace("&", "")
        anchor = "-".join(part for part in anchor.split("-") if part)
        lines.append(f"- [{category['name']}](#{anchor})")
    lines.append("")

    folded = []
    for category in REGISTRY.categories():
        lines += [f"## {category['name']}", ""]
        for spec in category["nodes"]:
            # A block folded into a bigger one is not offered any more; it
            # is listed at the end so an old graph's name can still be looked
            # up, but it gets no entry of its own.
            if spec.get("hidden"):
                folded.append(spec)
                continue
            lines += [f"### {spec['title']}", ""]
            hint = spec.get("flag_hint")
            lines.append(f"`{spec['type']}` · tool: `{spec['tool']}`"
                         + (f" · extra flags go to `{hint['command']}`" if hint else "")
                         + (f" · [docs]({spec['docs']})" if spec["docs"] else ""))
            lines += ["", escape(spec["description"]), ""]

            if spec["inputs"]:
                lines += ["| Input | Type | Required |", "|---|---|---|"]
                for port in spec["inputs"]:
                    lines.append(f"| {port['label']} | `{port['type']}` | "
                                 f"{'no' if port['optional'] else 'yes'} |")
                lines.append("")
            if spec["outputs"]:
                lines += ["| Output | Type |", "|---|---|"]
                for port in spec["outputs"]:
                    lines.append(f"| {port['label']} | `{port['type']}` |")
                lines.append("")

            visible = [p for p in spec["params"]
                       if p["name"] not in ("extra_flags", "env_override")]
            if visible:
                lines += ["| Parameter | Type | Default | Notes |", "|---|---|---|---|"]
                for param in visible:
                    default = param["default"]
                    default = "" if default in (None, "") else f"`{escape(str(default))}`"
                    kind = param["type"]
                    if param["choices"]:
                        kind += " (" + ", ".join(str(c) for c in param["choices"] if c != "") + ")"
                    note = escape(param["help"])
                    if param["advanced"]:
                        note = ("advanced. " + note).strip()
                    if param.get("form"):
                        # Worth saying in the reference: it is the difference
                        # between a box you have to know a syntax for and one
                        # you can answer questions into.
                        note = (note + " **Has a fill-in-the-blanks form** -- the "
                                "button under the box asks for this in "
                                "questions.").strip()
                    lines.append(f"| {param['label']} | {escape(kind)} | {default} | {note} |")
                lines.append("")

    lines += ["## Preconfigured chunks", "",
              "Drop-in subgraphs available from the Chunks tab of the palette.", "",
              "| Chunk | Category | Nodes | What it is |", "|---|---|---|---|"]
    for chunk in CHUNKS:
        lines.append(f"| {chunk['name']} | {chunk['category']} | "
                     f"{len(chunk['graph']['nodes'])} | {escape(chunk['description'])} |")
    lines.append("")

    lines += ["## mdp presets", "",
              "Starting points for the run-parameters node. Reference copies of each "
              "live in `comfygmx/mdp/`.", "",
              "| Preset | Integrator | dt (ps) | What it assumes |", "|---|---|---|---|"]
    for name, options in PRESETS.items():
        lines.append(f"| `{name}` | {options.get('integrator', '')} | "
                     f"{options.get('dt', '—')} | {escape(PRESET_INFO.get(name, ''))} |")
    lines.append("")

    target = ROOT / "docs" / "nodes.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    if folded:
        lines += ["## Blocks folded into others", "",
                  "These are kept so that older graphs still open, and they open as the "
                  "block named here with the right choice already made. They are not in "
                  "the palette.", "",
                  "| Old block | Now | Pick |", "|---|---|---|"]
        for spec in folded:
            swap = spec.get("replaced_by") or {}
            target_title = (REGISTRY.get(swap["type"]).title
                            if swap and REGISTRY.has(swap["type"]) else "-")
            pick = ", ".join(f"{k} = {v}" for k, v in (swap.get("params") or {}).items()) or "-"
            lines.append(f"| {spec['title']} (`{spec['type']}`) | {target_title} | {escape(pick)} |")
        lines.append("")
    target.write_text("\n".join(lines))
    print(f"wrote {target} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
