#!/usr/bin/env python3
"""Ask every tool the nodes drive for its flag list, and check the answers in.

The *Extra flags* box on a node shows the flags of the command that node
actually runs, with a one-line definition each.  Those definitions are not
written by us -- they come from ``gmx help <subcommand>``, from the
``add_argument`` calls of the scripts Comfy-gmx writes, and from ``--help`` on
the third-party programs.  This collects them into ``comfygmx/data/flags.json``.

Run it after adding a node with a new command, or against a newer GROMACS.
A command whose tool is not installed here keeps whatever the file already
says, so harvesting on a machine with half the toolchain does not throw the
other half away.

    python3 tools/harvest_flags.py --list        what would be asked, and who wants it
    python3 tools/harvest_flags.py               ask, and write the file
    python3 tools/harvest_flags.py --only gmx    just the commands matching
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from comfygmx import flaghints                 # noqa: E402
from comfygmx.config import Settings           # noqa: E402
from comfygmx.environments import Toolbox      # noqa: E402
from comfygmx.registry import REGISTRY         # noqa: E402


def users_of(command: str):
    return [t for t, cls in REGISTRY.items()
            if getattr(cls, "extra_command", "") == command]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true",
                        help="print the commands the nodes declare and stop")
    parser.add_argument("--only", default="",
                        help="harvest only commands containing this text")
    args = parser.parse_args()

    wanted = flaghints.commands_in_use(REGISTRY)
    if args.only:
        wanted = [c for c in wanted if args.only in c]
    if args.list:
        for command in wanted:
            nodes = users_of(command)
            print(f"{command:<34} {len(nodes):>2}  {', '.join(nodes)}")
        print(f"\n{len(wanted)} commands over {sum(len(users_of(c)) for c in wanted)} nodes")
        return 0

    stored = {}
    if flaghints.DATA_FILE.exists():
        stored = json.loads(flaghints.DATA_FILE.read_text()).get("commands") or {}
    commands = dict(stored)

    toolbox = Toolbox(Settings())
    failed = []
    for command in wanted:
        result = flaghints.harvest(command, toolbox)
        if result.get("error"):
            kept = len((commands.get(command) or {}).get("flags") or [])
            failed.append(command)
            print(f"  !! {command:<30} {result['error']}"
                  + (f" -- keeping the {kept} already stored" if kept else ""))
            continue
        entry = {"source": result["source"], "flags": result["flags"]}
        docs = next((cls.docs for t, cls in REGISTRY.items()
                     if getattr(cls, "extra_command", "") == command and cls.docs), "")
        if docs:
            entry["docs"] = docs
        commands[command] = entry
        print(f"  {command:<32} {len(result['flags']):>3} flags   {result['source']}")

    unused = [c for c in commands if c not in flaghints.commands_in_use(REGISTRY)]
    for command in unused:
        # A command no node runs any more: keeping it would quietly grow the
        # file with flags nothing can show.
        del commands[command]
        print(f"  -- dropped {command}: no node runs it")

    flaghints.DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    flaghints.DATA_FILE.write_text(json.dumps(
        {"note": "Generated by tools/harvest_flags.py -- do not edit by hand.",
         "commands": {k: commands[k] for k in sorted(commands)}},
        indent=1) + "\n")
    total = sum(len(v.get("flags") or []) for v in commands.values())
    print(f"\n{len(commands)} commands, {total} flags -> "
          f"{flaghints.DATA_FILE.relative_to(ROOT)}")
    if failed:
        print(f"{len(failed)} not installed here: {', '.join(failed)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
